DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TEST: ("custom_test",)
  TRAIN: ("custom_train",)
INPUT:
  DATASET_MAPPER_NAME: coco_instance_lsj
  FORMAT: RGB
  IMAGE_SIZE: 1024
  MAX_SCALE: 2.0
  MIN_SCALE: 0.1
MODEL:
  META_ARCHITECTURE: MaskDINO
  MaskDINO:
    BOX_WEIGHT: 5.0
    CLASS_WEIGHT: 4.0
    DEC_LAYERS: 9
    DEEP_SUPERVISION: true
    DICE_WEIGHT: 5.0
    DIM_FEEDFORWARD: 2048
    DN: seg
    DN_NUM: 100
    DROPOUT: 0.0
    ENC_LAYERS: 0
    ENFORCE_INPUT_PROJ: false
    EVAL_FLAG: 1
    GIOU_WEIGHT: 2.0
    HIDDEN_DIM: 256
    IMPORTANCE_SAMPLE_RATIO: 0.75
    INITIALIZE_BOX_TYPE: 'no'
    INITIAL_PRED: true
    MASK_WEIGHT: 5.0
    NHEADS: 8
    NO_OBJECT_WEIGHT: 0.1
    NUM_OBJECT_QUERIES: 300
    OVERSAMPLE_RATIO: 3.0
    PRE_NORM: false
    SIZE_DIVISIBILITY: 32
    TEST:
      INSTANCE_ON: true
      OBJECT_MASK_THRESHOLD: 0.25
      OVERLAP_THRESHOLD: 0.8
      PANOPTIC_ON: false
      SEMANTIC_ON: false
    TRAIN_NUM_POINTS: 12544
    TRANSFORMER_DECODER_NAME: MaskDINODecoder
    TWO_STAGE: true
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.5
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 256
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    DIM_FEEDFORWARD: 2048
    FEATURE_ORDER: low2high
    IGNORE_VALUE: 255
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    LOSS_WEIGHT: 1.0
    MASK_DIM: 256
    NAME: MaskDINOHead
    NORM: GN
    NUM_CLASSES: 8
    NUM_FEATURE_LEVELS: 3
    PIXEL_DECODER_NAME: MaskDINOEncoder
    TOTAL_NUM_FEATURE_LEVELS: 4
    TRANSFORMER_ENC_LAYERS: 6
OUTPUT_DIR: ./output
SOLVER:
  BASE_LR: 0.0001
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 0.01
    ENABLED: true
    NORM_TYPE: 2.0
  IMS_PER_BATCH: 1
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 50000
  OPTIMIZER: ADAMW
  STEPS: (30000, 40000)
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
TEST:
  EVAL_PERIOD: 500000
_BASE_: Base-COCO-InstanceSegmentation.yaml
